language: csharp
solution: Nancy.sln
sudo: false
install:
  - gem install bundle
  - bundle
  - mono tools/nuget/NuGet.exe restore Nancy.sln
  - echo \#\!/bin/bash >> ./travis.sh
  - echo set -e >> ./travis.sh
  - echo set -x >> ./travis.sh
  - echo set -o pipefail >> ./travis.sh
  - echo rake mono >> ./travis.sh
  - chmod +x ./travis.sh
  - cat travis.sh
script: ./travis.sh
notifications:
  email:
    - nancy@nancyfx.org
gemfile: Gemfile
